params:
  cuda_devices: []

optional_plugin_components: {}

shard_descriptor:
  template: market_shard_descriptor.MarketShardDescriptor
  params:
    datafolder: Market-1501-v15.09.15
    rank_worldsize: 2,2