params:
  cuda_devices: []

optional_plugin_components:
  cuda_device_monitor:
    template: openfl.plugins.processing_units_monitor.pynvml_monitor.PynvmlCUDADeviceMonitor
    settings: []

shard_descriptor:
  template: market_shard_descriptor.MarketShardDescriptor
  params:
    datafolder: Market-1501-v15.09.15
    rank_worldsize: 2,2