params:
  cuda_devices: []

optional_plugin_components: {}

shard_descriptor:
  template: medmnist_shard_descriptor.MedMNISTShardDescriptor
  params:
    rank_worldsize: 2, 2
    datapath: /home/nuc1/Documenti/DATASET
    dataname: bloodmnist
