# Copyright (C) 2020-2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

import shutil
import filecmp
from pathlib import Path
from openfl.experimental.workflow.notebooktools import NotebookTools

# Define paths
NOTEBOOK_PATH = "testcase_export/301_MNIST_Watermarking.ipynb"
ACTUAL_DIR = "testcase_export/test_artifacts/actual"
EXPECTED_DIR = "testcase_export/test_artifacts/expected"

def setup_workspace():
    """Setup function to create the actual workspace for testing."""
    # Ensure the actual directory is empty
    if Path(ACTUAL_DIR).exists():
        shutil.rmtree(ACTUAL_DIR)
    Path(ACTUAL_DIR).mkdir(parents=True, exist_ok=True)

    # Generate workspace using NotebookTools
    NotebookTools.export(
        notebook_path=NOTEBOOK_PATH,
        output_workspace=ACTUAL_DIR
    )

def compare_files(file1, file2):
    """Compare the content of two files, ignoring commentted lines."""
    with open(file1, "r") as f1, open(file2, "r") as f2:
        lines1 = f1.readlines()
        lines2 = f2.readlines()
        
        # Remove comment lines (lines starting with '#')
        lines1 = [line for line in lines1 if not line.startswith("#")]
        lines2 = [line for line in lines2 if not line.startswith("#")]

        return lines1 == lines2

def compare_directories(dir1, dir2):
    """Compare two directories recursively, including file content."""
    comparison = filecmp.dircmp(dir1, dir2)
    # Check for differences in file names or structure
    if comparison.left_only or comparison.right_only:
        return False

    # Compare subdirectories
    for subdir in comparison.common_dirs:
        if not compare_directories(Path(dir1) / subdir, Path(dir2) / subdir):
            return False

    # Compare file content for all common files
    for file in comparison.common_files:
        file1 = Path(dir1) / file
        file2 = Path(dir2) / file
        print(f"Comparing files: {file1} and {file2}")
        if not compare_files(file1, file2):
            return False

    return True

def test_export_functionality():
    """
    Test that the workspace generated by NotebookTools matches the Expected Artifacts.

    This function compares the contents of the actual directory generated by
    NotebookTools with the expected directory. 
    """
    # Compare the expected and actual directories
    assert compare_directories(EXPECTED_DIR, ACTUAL_DIR), (
        "The workspace generated by NotebookTools does not match the expected. "
        "Check the differences in the test_artifacts/expected and test_artifacts/actual folders."
    )

