# Copyright (C) 2020-2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

import shutil
import filecmp
from pathlib import Path
from openfl.experimental.workflow.runtime import FederatedRuntime
from openfl.experimental.workflow.notebooktools import NotebookTools

# Define paths
NOTEBOOK_PATH = "testcase_export_federated/MNIST_Watermarking.ipynb"
ACTUAL_DIR = "testcase_export_federated/test_artifacts/actual"
EXPECTED_DIR = "testcase_export_federated/test_artifacts/expected"

# Setup for FederatedRuntime
director_info = {
    'director_node_fqdn': 'localhost',
    'director_port': 50050,
}

authorized_collaborators = ['Bangalore', 'Chandler']

# Creating an instance of FederatedRuntime
federated_runtime = FederatedRuntime(
    collaborators=authorized_collaborators,
    director=director_info,
    notebook_path=NOTEBOOK_PATH,
    tls=False  # Actual testcase tls is set to false
)

def setup_workspace():
    """Setup function to create the actual workspace for testing."""
    # Ensure the actual directory is empty
    if Path(ACTUAL_DIR).exists():
        shutil.rmtree(ACTUAL_DIR)
    Path(ACTUAL_DIR).mkdir(parents=True, exist_ok=True)

    # Use the FederatedRuntime instance to get the parameters
    notebook_path = federated_runtime.notebook_path
    director_fqdn = federated_runtime.director["director_node_fqdn"]
    tls = federated_runtime.tls

    # Generate workspace using NotebookTools
    NotebookTools.export_federated(
        notebook_path=notebook_path,
        output_workspace=ACTUAL_DIR,
        director_fqdn=director_fqdn,
        tls=tls
    )

def compare_files(file1, file2):
    """Compare the content of two files, ignoring comment lines (lines starting with '#')."""
    with open(file1, "r") as f1, open(file2, "r") as f2:
        lines1 = f1.readlines()
        lines2 = f2.readlines()

        # Remove comment lines (lines starting with '#')
        lines1 = [line for line in lines1 if not line.startswith("#")]
        lines2 = [line for line in lines2 if not line.startswith("#")]

        return lines1 == lines2

def compare_directories(dir1, dir2):
    """Compare two directories recursively, including file content."""
    comparison = filecmp.dircmp(dir1, dir2)

    # Check for differences in file names or structure
    if comparison.left_only or comparison.right_only:
        return False

    # Compare subdirectories
    for subdir in comparison.common_dirs:
        if not compare_directories(Path(dir1) / subdir, Path(dir2) / subdir):
            return False

    # Compare file content for all common files
    for file in comparison.common_files:
        file1 = Path(dir1) / file
        file2 = Path(dir2) / file
        if not compare_files(file1, file2):
            return False

    return True

def test_export_federated_functionality():
    """Test that the workspace generated by NotebookTools matches the Expected Artifacts.

    This function compares the contents of the actual directory generated by
    NotebookTools with the expected directory.
    """ 
    # Compare the expected and actual directories
    assert compare_directories(EXPECTED_DIR, ACTUAL_DIR), (
        "The workspace generated by NotebookTools does not match the expected. "
        "Check the differences in the test_artifacts/expected and test_artifacts/actual folders."
    )