# This file is used to suppress both:
# * Trivy vulnerability scans (under the 'vulnerabilities' section).
# * Trivy's linting warnings (under the 'misconfigurations' section).
# For more information about the Trivy Ignore YAML file, please refer to:
# https://aquasecurity.github.io/trivy/v0.48/docs/configuration/filtering/#trivyignoreyaml
# Justification should be included above each suppression group.

######################## Trivy CVE supressions ########################
vulnerabilities:
  #   * Relevant packages:: libc-bin
  #   * These packages are part of Intel's latest official Ubuntu base image.
  - id: CVE-2025-0395

