# Copyright (C) 2020-2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
from openfl.component.straggler_handling_functions.straggler_handling_function import StragglerHandlingFunction
from openfl.component.straggler_handling_functions.cutoff_time_based_straggler_handling import CutoffTimeBasedStragglerHandling
from openfl.component.straggler_handling_functions.percentage_based_straggler_handling import PercentageBasedStragglerHandling
