settings:
  listen_host: localhost
  listen_port: 50050
  sample_shape: ['1'] # Modify this param if experimenting with `n_features` of shard_descriptor.
  target_shape: ['1']
  envoy_health_check_period: 5  # in seconds
