## Copyright (C) 2020-2021 Intel Corporation
# Licensed subject to the terms of the separately executed evaluation license agreement between Intel Corporation and you.

# all keys under 'collaborators' corresponds to a specific colaborator name the corresponding dictionary has data_name, data_path pairs.
# Note that in the mnist case we do not store the data locally, and the data_path is used to pass an integer that helps the data object
# construct the shard of the mnist dataset to be use for this collaborator.

# collaborator_name ,data_directory_path
col1:
  callable_func:
    settings:
      batch_size: 64
      index: 0
      n_collaborators: 4
      train_dataset: src.collaborator_private_attrs.train_dataset
      test_dataset: src.collaborator_private_attrs.test_dataset
    template: src.collaborator_private_attrs.callable_to_initialize_collaborator_private_attributes

col2:
  callable_func:
    settings:
      batch_size: 64
      index: 1
      n_collaborators: 4
      train_dataset: src.collaborator_private_attrs.train_dataset
      test_dataset: src.collaborator_private_attrs.test_dataset
    template: src.collaborator_private_attrs.callable_to_initialize_collaborator_private_attributes

col3:
  callable_func:
    settings:
      batch_size: 64
      index: 2
      n_collaborators: 4
      train_dataset: src.collaborator_private_attrs.train_dataset
      test_dataset: src.collaborator_private_attrs.test_dataset
    template: src.collaborator_private_attrs.callable_to_initialize_collaborator_private_attributes

col4:
  callable_func:
    settings:
      batch_size: 64
      index: 3
      n_collaborators: 4
      train_dataset: src.collaborator_private_attrs.train_dataset
      test_dataset: src.collaborator_private_attrs.test_dataset
    template: src.collaborator_private_attrs.callable_to_initialize_collaborator_private_attributes

aggregator:
  callable_func:
    settings:
      n_collaborators: 4
      batch_size: 64
      test_dataset: src.aggregator_private_attrs.test_dataset
    template: src.aggregator_private_attrs.callable_to_initialize_aggregator_private_attributes
