# Copyright (C) 2020-2021 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

# SETUP ENVOY PARAMETERS

# cuda_devices - field allows you to put indeces of cuda devices you want to allow using
#     in Federated experiments

# SETUP SHARD DESCRIPTOR
# To start envoy implement LocalShardDescriptor class in shard_descriptor module.
# Alternatively, point to an implemented Shard Descriptor in 'template' field.

# Put in 'params' group any argument needed to initialize choosen Shard Descriptor.
# Parameters are optional. For clarity, this example config contains three parameters:
# 1. data_path - string with data location on disk
# 2. sample_shape - shape of sample's numpy representaion that will by return from __getitem__ 
# 3. target_shape - shape of target's numpy representaion that will by return from __getitem__ 


params:
  install_requirements: true
  cuda_devices: []
  review_experiment: False

optional_plugin_components:
  cuda_device_monitor:
    template: openfl.plugins.processing_units_monitor.pynvml_monitor.PynvmlCUDADeviceMonitor
    settings: []

shard_descriptor:
  template: shard_descriptor.LocalShardDescriptor
  params:
    data_path: data
    sample_shape: []
    target_shape: []