# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import preparations_pb2 as preparations__pb2


class FederationDirectorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AcknowledgeShard = channel.unary_unary(
                '/FederationDirector/AcknowledgeShard',
                request_serializer=preparations__pb2.ShardInfo.SerializeToString,
                response_deserializer=preparations__pb2.ShardAcknowledgement.FromString,
                )
        self.SetNewExperiment = channel.stream_unary(
                '/FederationDirector/SetNewExperiment',
                request_serializer=preparations__pb2.ExperimentInfo.SerializeToString,
                response_deserializer=preparations__pb2.Response.FromString,
                )
        self.GetRegisterdShards = channel.unary_unary(
                '/FederationDirector/GetRegisterdShards',
                request_serializer=preparations__pb2.GetRegisterdShardsRequest.SerializeToString,
                response_deserializer=preparations__pb2.GetRegisterdShardsResponse.FromString,
                )
        self.WaitExperiment = channel.stream_stream(
                '/FederationDirector/WaitExperiment',
                request_serializer=preparations__pb2.WaitExperimentRequest.SerializeToString,
                response_deserializer=preparations__pb2.WaitExperimentResponse.FromString,
                )
        self.GetExperimentData = channel.unary_stream(
                '/FederationDirector/GetExperimentData',
                request_serializer=preparations__pb2.GetExperimentDataRequest.SerializeToString,
                response_deserializer=preparations__pb2.ExperimentData.FromString,
                )


class FederationDirectorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AcknowledgeShard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetNewExperiment(self, request_iterator, context):
        """Shard owner could also provide some public data for tests
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRegisterdShards(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WaitExperiment(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetExperimentData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FederationDirectorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AcknowledgeShard': grpc.unary_unary_rpc_method_handler(
                    servicer.AcknowledgeShard,
                    request_deserializer=preparations__pb2.ShardInfo.FromString,
                    response_serializer=preparations__pb2.ShardAcknowledgement.SerializeToString,
            ),
            'SetNewExperiment': grpc.stream_unary_rpc_method_handler(
                    servicer.SetNewExperiment,
                    request_deserializer=preparations__pb2.ExperimentInfo.FromString,
                    response_serializer=preparations__pb2.Response.SerializeToString,
            ),
            'GetRegisterdShards': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRegisterdShards,
                    request_deserializer=preparations__pb2.GetRegisterdShardsRequest.FromString,
                    response_serializer=preparations__pb2.GetRegisterdShardsResponse.SerializeToString,
            ),
            'WaitExperiment': grpc.stream_stream_rpc_method_handler(
                    servicer.WaitExperiment,
                    request_deserializer=preparations__pb2.WaitExperimentRequest.FromString,
                    response_serializer=preparations__pb2.WaitExperimentResponse.SerializeToString,
            ),
            'GetExperimentData': grpc.unary_stream_rpc_method_handler(
                    servicer.GetExperimentData,
                    request_deserializer=preparations__pb2.GetExperimentDataRequest.FromString,
                    response_serializer=preparations__pb2.ExperimentData.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'FederationDirector', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FederationDirector(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AcknowledgeShard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/FederationDirector/AcknowledgeShard',
            preparations__pb2.ShardInfo.SerializeToString,
            preparations__pb2.ShardAcknowledgement.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetNewExperiment(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/FederationDirector/SetNewExperiment',
            preparations__pb2.ExperimentInfo.SerializeToString,
            preparations__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetRegisterdShards(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/FederationDirector/GetRegisterdShards',
            preparations__pb2.GetRegisterdShardsRequest.SerializeToString,
            preparations__pb2.GetRegisterdShardsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def WaitExperiment(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/FederationDirector/WaitExperiment',
            preparations__pb2.WaitExperimentRequest.SerializeToString,
            preparations__pb2.WaitExperimentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetExperimentData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/FederationDirector/GetExperimentData',
            preparations__pb2.GetExperimentDataRequest.SerializeToString,
            preparations__pb2.ExperimentData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
