# Copyright (C) 2020-2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

import shutil
import filecmp
from pathlib import Path
import pytest
from openfl.experimental.workflow.notebooktools import NotebookTools

class bcolors:
    HEADER = "\033[95m"
    OKBLUE = "\033[94m"
    OKCYAN = "\033[96m"
    OKGREEN = "\033[92m"
    WARNING = "\033[93m"
    FAIL = "\033[91m"
    ENDC = "\033[0m"
    BOLD = "\033[1m"
    UNDERLINE = "\033[4m"

# Define paths
NOTEBOOK_PATH = "tests/openfl/experimental/workflow/NotebookTools/testcase_export/test_101_MNIST.ipynb"
ACTUAL_DIR = "tests/openfl/experimental/workflow/NotebookTools/testcase_export/test_artifacts/actual"
EXPECTED_DIR = "tests/openfl/experimental/workflow/NotebookTools/testcase_export/test_artifacts/expected"

@pytest.fixture
def setup_workspace():
    """Setup function to create the actual workspace for testing."""

    print(f"{bcolors.OKBLUE}Setting up the workspace.{bcolors.ENDC}")
    # Ensure the actual directory is empty
    if Path(ACTUAL_DIR).exists():
        shutil.rmtree(ACTUAL_DIR)
    Path(ACTUAL_DIR).mkdir(parents=True, exist_ok=True)
    print(f"{bcolors.OKGREEN}Workspace setup complete.{bcolors.ENDC}")

def validate_generated_workspace():
    """Validate that the generated workspace matches the expected artifacts."""
    print(f"{bcolors.OKBLUE}Validating the generated workspace.{bcolors.ENDC}")

    # Compare the expected and actual directories
    if not compare_directories(EXPECTED_DIR, ACTUAL_DIR):
        print(f"{bcolors.FAIL}❌ Test failed - The workspace generated by NotebookTools export does not match the expected.{bcolors.ENDC}")
        assert False, "The workspace generated by NotebookTools export functionality does not match the expected."
    else:
        print(f"{bcolors.OKGREEN}✔️ Test passed - The generated workspace matches the expected artifacts.{bcolors.ENDC}")
        shutil.rmtree(ACTUAL_DIR)
        print(f"{bcolors.OKGREEN}Cleanup complete - The actual directory has been removed.{bcolors.ENDC}")

def compare_files(file1, file2):
    """Compare the content of two files, ignoring comment lines."""
    with open(file1, "r") as f1, open(file2, "r") as f2:
        lines1 = f1.readlines()
        lines2 = f2.readlines()

        # Remove comment lines (lines starting with '#') and trailing whitespace
        lines1 = [line.rstrip() for line in lines1 if not line.startswith("#")]
        lines2 = [line.rstrip() for line in lines2 if not line.startswith("#")]

        if lines1 == lines2:
            print(f"{bcolors.OKGREEN}✅ Successfully compared: {file1} and {file2}{bcolors.ENDC}")
            return True
        else:
            print(f"{bcolors.FAIL}Comparison failed: {file1} and {file2}{bcolors.ENDC}")
            print(f"{bcolors.FAIL}Differences:{bcolors.ENDC}")
            for line1, line2 in zip(lines1, lines2):
                if line1 != line2:
                    print(f"{bcolors.FAIL}Expected: {line1.strip()}{bcolors.ENDC}")
                    print(f"{bcolors.FAIL}Actual: {line2.strip()}{bcolors.ENDC}")
            return False

def compare_directories(dir1, dir2):
    """Compare two directories recursively, including file content."""
    comparison = filecmp.dircmp(dir1, dir2)

    # Check for differences in file names or structure
    if comparison.left_only or comparison.right_only:
        print(f"{bcolors.FAIL}Differences found in directory structure: {comparison.left_only} only in {dir1}, {comparison.right_only} only in {dir2}{bcolors.ENDC}")
        return False

    # Compare subdirectories, excluding __pycache__
    for subdir in comparison.common_dirs:
        if subdir == "__pycache__":
            continue
        if not compare_directories(Path(dir1) / subdir, Path(dir2) / subdir):
            return False

    # Compare file content for all common files
    for file in comparison.common_files:
        file1 = Path(dir1) / file
        file2 = Path(dir2) / file
        print(f"{bcolors.OKCYAN} Comparing files of expected and generated workspace.{bcolors.ENDC}")
        if not compare_files(file1, file2):
            return False

    return True

def test_export_functionality(setup_workspace):
    """
    Test the workspace generated by NotebookTools export functionality matches the Expected Artifacts.
    This function compares the contents of the actual directory generated by
    NotebookTools with the expected directory.
    """
    # NotebookTools export generate the workspace.
    print(f"{bcolors.OKBLUE}Calling ... NotebookTools export functionality to generate the actual workspace.{bcolors.ENDC}")

    NotebookTools.export(
        notebook_path=NOTEBOOK_PATH,
        output_workspace=ACTUAL_DIR
    )
    print(f"{bcolors.OKGREEN}NotebookTools execution complete.{bcolors.ENDC}")

    # Validate that the generated workspace matches the expected output
    validate_generated_workspace()
