# https://www.gutenberg.org/cache/epub/7439/pg7439-images.html
params:
  cuda_devices: []

optional_plugin_components: {}

shard_descriptor:
  template: shard_descriptor.NextWordShardDescriptor
  params:
    title: English Fairy Tales
    author: Joseph Jacobs