# https://www.gutenberg.org/files/36668/36668-h/36668-h.htm
params:
  cuda_devices: []

optional_plugin_components: {}

shard_descriptor:
  template: shard_descriptor.NextWordShardDescriptor
  params:
    title: Polish Fairy Tales
    author: A. J. Gliński