sequenceDiagram
    participant D as Director
    participant E as Envoy
    rect rgb(0, 255, 0,.1)
        Note over D,E: A Federation startup process
        D->D: Starts
        E->E: Starts and loads local Shard Descriptor
        E-->>D: Connects using FQDN and certificate
        E-->>+D: Communicates dataset info
        D-->D: Ensures unified data interface
        D-->>-E: Approves
        D-->D: Keeps a list of connected Envoys
        
    end
    Note over D,E: We consider a Federation set up
    rect rgb(0, 0, 255,.05)
        Note over D,E: An Experiment's start
        D->D: Registers a model, FL tasks and an FL plan
        D->D:Starts an Aggregator with a toy plan
        Note left of D: An Envoy with dummy data is <br>started locally
        opt Test run failed
            D-->D: Notifies user that <br>the experiment is inconsistent
            D-->D: The experiment ends
        end
        D->D: Reviews the FL plan
        D->D: Starts an Aggregator
        D-->>E: Sends the experiment archive <br>and the FL plan to envoys
        E-->E: Reviews the FL Plan
        E-->E: Starts a Collaborator
        D-->D: Fills the model with the final weights <br>and returns to user
    end
    Note over D,E: The Experiment ended. <br> The Federation keeps existing.