## Copyright (C) 2020-2021 Intel Corporation
# Licensed subject to the terms of the separately executed evaluation license agreement between Intel Corporation and you.

# all keys under 'collaborators' corresponds to a specific colaborator name the corresponding dictionary has data_name, data_path pairs.
# Note that in the mnist case we do not store the data locally, and the data_path is used to pass an integer that helps the data object
# construct the shard of the mnist dataset to be use for this collaborator.

# collaborator_name ,data_directory_path
col1:
  callable_func:
    settings:
      batch_size: 32
      index: 0
      n_collaborators: 2
      test_dataset: src.collaborator_private_attrs.test_dataset
      train_dataset: src.collaborator_private_attrs.train_dataset
    template: src.collaborator_private_attrs.collaborator_private_attrs

col2:
  callable_func:
    settings:
      batch_size: 32
      index: 1
      n_collaborators: 2
      test_dataset: src.collaborator_private_attrs.test_dataset
      train_dataset: src.collaborator_private_attrs.train_dataset
    template: src.collaborator_private_attrs.collaborator_private_attrs
