# Copyright (C) 2020-2021 Intel Corporation
# Licensed subject to the terms of the separately executed evaluation license agreement between Intel Corporation and you.

aggregator :
  defaults : plan/defaults/aggregator.yaml
  template : openfl.component.Aggregator
  settings :
    init_state_path : save/init.pbuf
    last_state_path : save/latest.pbuf
    best_state_path : save/best.pbuf
    db_store_rounds : 2
    rounds_to_train : 10

collaborator :
  defaults : plan/defaults/collaborator.yaml
  template : openfl.component.Collaborator
  settings :
    delta_updates    : true
    db_store_rounds: 2
    opt_treatment    : RESET

data_loader :
  defaults : plan/defaults/data_loader.yaml
  template : src.dataloader.HistologyDataloader
  settings :
    batch_size: 64
    percent_train: 0.8
    collaborator_count : 2
    data_group_name    : histology

task_runner :
  defaults : plan/defaults/task_runner.yaml
  template : src.taskrunner.CNN

network :
  defaults : plan/defaults/network.yaml

assigner :
  defaults : plan/defaults/assigner.yaml

tasks:
  defaults: plan/defaults/tasks_tensorflow.yaml
  aggregated_model_validation:
    function: validate_task
    kwargs:
      apply: global
      batch_size: 32
      metrics:
      - sparse_categorical_accuracy
  locally_tuned_model_validation:
    function: validate_task
    kwargs:
      apply: local
      batch_size: 32
      metrics:
      - sparse_categorical_accuracy
  settings: {}
  train:
    function: train_task
    kwargs:
      batch_size: 32
      epochs: 1
      metrics:
      - loss