sequenceDiagram
Title: Collaborator Certificate Signing Flow
  participant A as Aggregator
  participant CA as CA
  participant C as Collaborator
  CA->>CA: 1. Create CA:<br>`cfssl gencert -initca csr_ca.json`
  CA->>CA: 2. Create server key pair for tls connection (between CA and clients):<br>cfssl gencert -ca=ca.pem -ca-key=ca-key.pem  -hostname='localhost' csr_server.json
  CA->>CA: 3. Create auth key:<br>`echo -n $(openssl rand -hex 16 | tr -d '\n') > base.key` to generate auth_key
  CA->>CA: 4. Up HTTPS CA server:<br>`cfssl serve -ca-key ca-key.pem -ca ca.pem -tls-key server-key.pem -tls-cert server.pem -config config_ca.json` <br> to up CA server
  CA->>C: 5. In untrusted area: manually deliver CA cert.<br>In trusted area use:`cfssl info -remote ca_host:8888`
  Note over C,CA: Get ca.pem
  CA->>A: 6. In untrusted area: manually deliver CA cert.<br>In trusted area use:`cfssl info -remote ca_host:8888`
  Note over A,CA: Get ca.pem
  A->>CA: 7. Generate and sign aggregator cert (over tls):<br>`cfssl gencert -hostname='host' -tls-remote-ca ca.pem -config config_server.json csr_server.json`
  Note over A,CA: Get signed agg.pem 
  C->>CA: 8. Generate and sign collaborator cert (over tls):<br>`cfssl gencert -tls-remote-ca ca.pem -config config_client.json csr_client.json`
  Note over C,CA: Get signed col.pem 
  