FROM python:3.8

COPY . ./code
WORKDIR code

RUN pip install --upgrade pip
RUN pip install git+https://github.com/intel/openfl.git@dockerezation-launch
RUN pip install --no-cache-dir -r requirements.txt
