settings:
  cuda_devices: []

optional_plugin_components: {}

shard_descriptor:
  template: medmnist_shard_descriptor.MedMNISTShardDescriptor
  settings:
    rank_worldsize: 1, 1
    datapath: data/.
    dataname: synapsemnist3d
