name: OSPDT Dependency Workflow

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to tag the Docker image with'
        required: false
        default: 'latest'

env:
  VERSION: ${{ github.ref == 'refs/heads/develop' && 'latest' || '1.7' }}

permissions:
  contents: read
  packages: write

jobs:

  set-images:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and Push OpenFL Base Image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: openfl-docker/Dockerfile.base