---
# Publish nightly package to PyPI

name: Publish Nightly Package to PyPI

on:
  workflow_call:
    inputs:
      commit_id:
        required: false
        type: string
    secrets:
      PYPI_API_TOKEN:
        required: true
  workflow_dispatch:
    inputs:
      commit_id:
        required: false
        type: string
        description: "Commit ID to use for the nightly build"

env:
  COMMIT_ID: ${{ inputs.commit_id || github.sha }} # use commit_id from the calling workflow

permissions:
  id-token: write

jobs:
  publish_package:
    name: Publish Nightly Package
    runs-on: ubuntu-22.04
    environment: dev
    if: |
      (github.event_name == 'schedule' && github.repository_owner == 'securefederatedai') ||
      (github.event_name == 'workflow_dispatch')
    steps:
    - name: Checkout OpenFL repository
      uses: actions/checkout@v4
      with:
        ref: ${{ env.COMMIT_ID }}

    - name: Modify setup.py for nightly build
      run: |
        echo "Creating package..."
        version=$(grep -oP "(?<=version=')[^']+" setup.py)
        date_suffix=$(date +%Y%m%d)
        new_version="${version}${date_suffix}"
        sed -i 's/name=.*/name="openfl-nightly",/' setup.py
        sed -i "s/version=.*/version='$new_version',/" setup.py
        sed -i 's/Development Status :: 5 - Production\/Stable/Development Status :: 4 - Beta/' setup.py

    - name: Build package
      run: |
        python3 -m pip install setuptools wheel twine --upgrade build
        python3 -m pip install .
        python3 -m build
        echo "Package built successfully!"

    - name: Upload package to PyPI
      run: |
        python3 -m twine upload dist/openfl_nightly* --verbose -u __token__ -p ${{ secrets.PYPI_API_TOKEN }}
        echo "Package published successfully!"
