# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Continuous Integration

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install -r requirements-test.txt
        pip install .
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest    
    - name: Interactive API - tensorflow_mnist
      run: |
        python setup.py build_grpc
        pip install tensorflow==2.8
        cd tests/github/interactive_api_director/experiments/tensorflow_mnist
        ./run.sh
        pkill fx
    - name: Interactive API - pytorch_kvasir_unet
      run: |
        python setup.py build_grpc
        pip install torch==1.7.1
        pip install torchvision==0.8.2
        cd tests/github/interactive_api_director/experiments/pytorch_kvasir_unet
        ./run.sh
        pkill fx
    - name: Test TaskRunner API
      run: |
        bash tests/github/test_hello_federation.sh keras_cnn_mnist aggregator col1 col2 $(hostname --all-fqdns | awk '{print $1}') --rounds-to-train 3
    - name: Test Straggler Handling Interface
      run: |
        bash tests/github/test_hello_federation.sh torch_cnn_mnist_straggler_check aggregator col1 col2 $(hostname --all-fqdns | awk '{print $1}') --rounds-to-train 3
    - name: Setup FeTS Challenge Prerequisites
      uses: actions/checkout@master
      with:
          repository: CBICA/GaNDLF
          ref: 0.0.14
          fetch-depth: 1
          path: fets_challenge
    - name: FeTS Challenge Task Runner Test
      run: |
        cd fets_challenge
        pwd
        pip install torch==1.8.2+cpu torchvision==0.9.2+cpu torchaudio===0.8.2 -f https://download.pytorch.org/whl/lts/1.8/torch_lts.html
        pip install -e .
        # Download data and Split CSVs into training and validation
        python -c "from testing.test_full import test_generic_download_data, test_generic_constructTrainingCSV; test_generic_download_data(); test_generic_constructTrainingCSV()"
        head -n 1 testing/data/train_3d_rad_segmentation.csv > /home/runner/work/openfl/openfl/seg_test_val.csv
        tail -n +9 testing/data/train_3d_rad_segmentation.csv >> /home/runner/work/openfl/openfl/seg_test_val.csv
        head -n 8 testing/data/train_3d_rad_segmentation.csv > /home/runner/work/openfl/openfl/seg_test_train.csv
        cd /home/runner/work/openfl/openfl
        ls
        bash tests/github/test_fets_challenge.sh fets_challenge_seg_test aggregator col1 col2 $(hostname --all-fqdns | awk '{print $1}') --rounds-to-train 1
        
