# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: TaskRunner

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: read

env:
  # A workaround for long FQDN names provided by GitHub actions.
  FQDN: "localhost"

jobs:
  build:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies ubuntu
      run: |
        python -m pip install --upgrade pip
        pip install .
    - name: Create certificate authority for workspace
      run: |
          cd ${PWD}/openfl-workspace/torch_cnn_mnist
          fx workspace certify
    - name: Setup Aggregator
      run: |
          cd ${PWD}/openfl-workspace/torch_cnn_mnist
          fx aggregator generate-cert-request --fqdn localhost
          fx aggregator certify --fqdn localhost --silent
    - name: Setup Collaborator 1 
      run: |
          cd ${PWD}/openfl-workspace/torch_cnn_mnist
          fx collaborator create -n collaborator1 -d 1
          fx collaborator generate-cert-request -n collaborator1
          fx collaborator certify -n collaborator1 --silent
    - name: Setup Collaborator 2 
      run: |
          cd ${PWD}/openfl-workspace/torch_cnn_mnist
          fx collaborator create -n collaborator2 -d 2
          fx collaborator generate-cert-request -n collaborator2
          fx collaborator certify -n collaborator2 --silent
    - name: Run Federation
      run: |
          cd ${PWD}/openfl-workspace/torch_cnn_mnist
          fx aggregator start & fx collaborator start -n collaborator1 & fx collaborator start -n collaborator2