name: Trivy
on:
  push:
    branches: [ develop ]
  pull_request:
jobs:
  build:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build an image from Dockerfile
        run: |
          docker build --pull -t docker.io/securefederatedai/openfl:${{ github.sha }} -f openfl-docker/Dockerfile.base .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: 'docker.io/securefederatedai/openfl:${{ github.sha }}'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Run Trivy code vulnerability scanner (JSON Output)
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: ''
          format: 'json'
          output: 'trivy-code-results.json'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH,MEDIUM,LOW'

      - name: Upload Code Vulnerability Scan Results
        uses: actions/upload-artifact@v3
        with:
          name: trivy-code-report-json
          path: trivy-code-results.json
      
      - name: Run Trivy vulnerability scanner for Docker image
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: 'docker.io/securefederatedai/openfl:${{ github.sha }}'
          format: 'csv'
          output: 'trivy-docker-results.csv'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH,MEDIUM,LOW'
  
      - name: Upload Docker Vulnerability Scan
        uses: actions/upload-artifact@v3
        with:
          name: trivy-docker-report-csv
          path: trivy-docker-results.csv
